export default [
    "fghfjg",
    "ryewiuy@gmail.com",
    "rye4546y@gmail.ru",
    "rety@mail.ru",
    "rety@mail.ua",
    "rety@mail.ruka",
    "1132423",
    "96586%tyr.com",
    "klit@tuyrtiu.com",
    "asdf@yandex.ru",
    "4567yut@yandex.th",
    "nvbd@yandex",
    "@vbcnmsk@yandex.com",
    "hotline@ukr.net",
    "dsar@$ukr.net",
    "gug@rambler.ru",
    "__fou@rambler.ru",
    "vbnc%rambler.ru",
    "рапао@gmail.com",
    "арвлаопр@ukr.net",
    "ghrty'fhhg@rambler.ru",
  ];

